#!/usr/bin/env python3

__author__ = "konstantinos.prasopoulos@epfl.ch (konstantinos prasopoulos)"

'''
Work in progress
'''

import csv
import os
import sys
from pprint import pprint


def get_all_instances(rows, key):
    instances = set()
    for row in rows:
        instances.update([row[key]])
    return list(instances)


def main():
    file = "report.csv"
    rows = []
    with open(file) as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            rows.append(row)
    pprint(rows)
    accounts = get_all_instances(rows, "Account")
    coins = get_all_instances(rows, "Coin")
    print(accounts)
    print(coins)


if __name__ == "__main__":
    main()
