#!/usr/bin/env python3

__author__ = "konstantinos.prasopoulos@epfl.ch (konstantinos prasopoulos)"

'''
Work in progress
'''

import os
import sys
from pprint import pprint

import util
import trade_processor as tradep
import transaction_processor as transp
from cfg import trcols, tdcols


def print_monthly_results(res):
    print("\n================= RESULTS =================")
    for res_key in res:
        print(f"\n\n>>>>>>>> {res_key} <<<<<<<<")
        for month in res[res_key]:
            print(f"\n>>>>>> {month}")
            for data_key in res[res_key][month]:
                values = res[res_key][month][data_key]
                if len(values) > 0:
                    print(f">> {data_key}")
                    pprint(values)


def print_info(res):
    print(f"\n~~~~~~~~~~~~~~~ INFO ~~~~~~~~~~~~~~~")
    for res_key in res:
        print(f"\n\n>>>>>>>> {res_key} <<<<<<<<\n")
        for info_key in res[res_key]:
            print(f">> {info_key}")
            print(res[res_key][info_key])

# def aggregate_monthly_results(monthly_results):
#     '''
#     Expects a dictionary keyed by month. Each value is a dictionary keyed by 

def main():
    # TODO: CLI args
    transaction_filepath = "transaction_history_2.csv"
    order_filepath = "order_history.csv"
    trade_filepath = "trade_history.csv"
    do_print_info = True

    monthly_results = {}
    results = {}
    info = {}
    monthly_results["Transaction History"], info["Transaction History"] = transp.process_transaction_history(
        transaction_filepath)
    monthly_results["Trade History"], info["Trade History"] = tradep.process_trade_history(
        trade_filepath, info["Transaction History"]["Coins"])
    

    if do_print_info:
        print_info(info)
    print_monthly_results(monthly_results)


if __name__ == "__main__":
    main()
